[package]
name = "monos"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
bootloader-boot-config = "0.11"
monos_kernel = { path = "monos_kernel", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = [ "font_gen","monos_kernel"]

resolver = "2"
