// this is kinda stupid but it is what it is
use minifb::Key;
pub fn char_to_key(c: char) -> Key {
    match c.to_ascii_lowercase() {
        'a' => Key::A,
        'b' => Key::B,
        'c' => Key::C,
        'd' => Key::D,
        'e' => Key::E,
        'f' => Key::F,
        'g' => Key::G,
        'h' => Key::H,
        'i' => Key::I,
        'j' => Key::J,
        'k' => Key::K,
        'l' => Key::L,
        'm' => Key::M,
        'n' => Key::N,
        'o' => Key::O,
        'p' => Key::P,
        'q' => Key::Q,
        'r' => Key::R,
        's' => Key::S,
        't' => Key::T,
        'u' => Key::U,
        'v' => Key::V,
        'w' => Key::W,
        'x' => Key::X,
        'y' => Key::Y,
        'z' => Key::Z,
        '0' => Key::Key0,
        '1' => Key::Key1,
        '2' => Key::Key2,
        '3' => Key::Key3,
        '4' => Key::Key4,
        '5' => Key::Key5,
        '6' => Key::Key6,
        '7' => Key::Key7,
        '8' => Key::Key8,
        '9' => Key::Key9,
        ' ' => Key::Space,
        '\n' => Key::Enter,
        _ => Key::Unknown,
    }
}
