[package]
name = "monos_std"
version = "0.1.0"
edition = "2021"

[dependencies]
linked_list_allocator = "0.10.5"
monos_gfx = { path = "../monos_gfx" }
num_enum = { version = "0.7.2", default-features = false }


[features]
default-features = []
lib_only = []
