[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
monos_std = { path = "../../monos_std" }
monos_gfx = { path = "../../monos_gfx" }

monoscript = { path = "../../monoscript" }
rooftop = { path = "../rooftop", features = ["client"] }
