[package]
name = "monos_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11"
linked_list_allocator = "0.10.5"
pc-keyboard = "0.7.0"
spin = "0.9.8"
take-static = "0.1.2"
uart_16550 = "0.3.0"
x86_64 = "0.15.1"
