[package]
name = "doom"
version = "0.1.0"
edition = "2021"

[dependencies]
monos_std = { path = "../../monos_std" }
monos_gfx = { path = "../../monos_gfx" }

rooftop = { path = "../rooftop", features = ["client"] }

[build-dependencies]
cc = "1.0"


