[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.59"
quote = "1.0.28"
syn = { version = "2.0", features = ["full"] }
paste = "1.0.12"

[lib]
proc-macro = true
